### ISSUE TITLE
[CHORE] Create UI/UX designs for Signup Page

### ISSUE THREAD

**Issue by kmwamasali** [BuildForSDG/farmrail#18]
Is your feature request related to a problem? Please describe.
Create a mock designs for the signup page 

Describe the solution you'd like
Should use material design consistent with the dev spec

**Comment by amkayondo** [comment]
Added needed fields for a user to create a new account

### Farmrail Signup Desktop
![FarmrailSignup-Desktop (2)](https://user-images.githubusercontent.com/46356108/81302565-36a32b00-9083-11ea-814b-890be8131023.png)

### Farmrail Signup Mobile
![FarmrailSignup-mobile (1)](https://user-images.githubusercontent.com/46356108/81302558-3571fe00-9083-11ea-9278-5b41658f8dd0.png)
