### ISSUE TITLE
[CHORE] Create UI/UX Designs for farmers' dashboard on Login

### ISSUE THREAD

**Issue by swimking** [BuildForSDG/farmrail#25]
**Designing of a screen mockup to help the UI team Visualize how the screen should look.**
**Deliverable**
A well-designed mockup for the screen

**Comment by swimking** [comment]
Any design tool can be used

**Comment by amkayondo** [comment]
**Added UI elements for the products and other functionality** 

![Farmrail - DashBoardDashBoard-Desktop (3)](https://user-images.githubusercontent.com/46356108/81963750-37593580-961e-11ea-9d5d-eecf421149be.png)
