### ISSUE TITLE
[CHORE] Create the UI/UX Designs for the login Page

### ISSUE THREAD

**Issue by kmwamasali** [BuildForSDG/farmrail#4]
**Is your feature request related to a problem? Please describe.**
We need a clean and modern design for the login page

**Describe the solution you'd like**
Something standard like the material designs

**Comment by amkayondo** [comment]
### Added Login elements to Login Design

- Farmrail Logo
- Login Inputs
- Social Icons for social Login
- Image of a farmer
- Reset Password Link
- Create New Account Link

![image](https://user-images.githubusercontent.com/46356108/81223945-90f2ac00-8fef-11ea-9824-2242006e9652.png)
