### ISSUE TITLE
[CHORE] Create UI/UX Design for not logged in dashboard menu

### ISSUE THREAD

**Issue by amkayondo** [BuildForSDG/farmrail#45]
**Designing of a screen mockup to help the UI team Visualize how the dashboard menu when the user is not logged in should look.**
**Deliverable**
A well-designed mockup for the screen

**Comment by amkayondo** [comment]
**added shortcuts to the market place, login and signup**

![FarmernotLoggedin-DashBoard](https://user-images.githubusercontent.com/46356108/81962210-1859a400-961c-11ea-8cdf-cc6b6b7d82a6.png)

**Comment by kmwamasali** [comment]
Fixes #10
